package analysisTool;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextArea;

public class AboutFrame extends JDialog {

    public AboutFrame(JFrame parent) {
        super(parent);
        initComponents();
    }

    private void initComponents() {
        JPanel panel = new JPanel();
        
    	setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JTextArea instructions = new JTextArea();
        instructions.setEditable(false);
        setSize(new Dimension(900,300));
        
    	instructions.setText("Tool for analyzing the data which was "
    			+ "generated by the multi-touch system. ");
        setTitle("About");
        setModal(true);
        setResizable(false);
        
        panel.add(instructions);
        panel.add(new JSeparator());
        panel.add(new JLabel("Created by Andrew McGlynn 2011 (c)"));
        add(panel);
    }
}
